Speed up setup step by running scripts in parallel
swellstores/horizon pull request #23
Opened 2022-12-22 14:34 UTC by AdrianRC

This MR refactors the setup npm scripts to run in parallel and makes use of the dotenv cli to load the environment variables in a cross-platform compatible way. The previous version did not work well on Windows and some shells.

2022-12-22 16:52 UTC, cristianstanescu approved these changes

2023-01-03 18:49 UTC, rodrigoddalmeida requested changes

2023-01-03 18:49 UTC, rodrigoddalmeida commented on package.json
> +    "setup": "concurrently \"npm:sync\" \"npm:graphql:generate\" \"npm:theme:generate\"",
Wouldn't `sync` need to run before `graphql:generate` (so the model schema is up to date)? Running them concurrently might not assert that.

2023-01-04 16:50 UTC, alextutii approved these changes

2023-04-28 14:45 UTC, closed without merging