Draft: Feat: add language settings
swellstores/horizon pull request #24
Opened 2023-01-06 12:40 UTC by alextutii

2023-01-10 11:45 UTC, cristianstanescu requested changes
I think we can make a few improvements before merging this one:

1. unit tests and documentation for /utils folder. We should make sure it is easy to understand what to expect when using those functions.

2. further on documentation: [README.md](http://readme.md/) should describe how language settings work and update any changes. Also add short instructions for how to add & use a new language string for example.

3. there's currently a lot of repetition and some language strings are loaded in component files, others in utils/lang.ts. It is unclear why this needs to happen. Is it for Storybook? Regardless, we should think of a different approach, i.e. all strings should be in one place.

4. the main issue however and related to 3. is that the approach is too hard coded. We should improve it so that things are easier to work with. For example, adding a new string should only require an entry in config/defaults.json. One way to do it is having a single function that deals with the language, e.g.:

    ```
    i18n('account.orders.empty.label') // no variable
    i18n('categories.product_count', {count}) // with variable
    ```

    The function can/should be "smart" enough to try and load from the db (store settings) or from the defaults.json. It should also know how to replace variables. This way, we can avoid all the duplication around this pattern:

    ```
    const lang = useSettingsStore((state) => state.settings?.lang);

    const productCountLabel = fallbackString(
        lang?.categories?.productCount,
        'All products ({count})',
    );
    const parsedProductCountLabel = parseTextWithVariables(productCountLabel, {
        count: count.toString(),
    });
    ```

    which will make the code more readable, reduce the size of the addition (most of what is present in utils/lang.ts) and easier to extend.

2023-01-10 11:45 UTC, cristianstanescu commented on components/atoms/ProductCount/ProductCount.tsx
> +  });
We should have one place only to parse these `lang` objects & configs, we already have quite a bunch in utils/lang.ts.

We can also simplify the approach here, something like `i18n('categories.product_count', {count})` should be more desirable and easier to work with.

2023-01-11 17:18 UTC, alextutii commented on lib/utils/fetch_decorators.ts
> +    const editorData = await import('mock/editor.json');
@cristianstanescu we'll need to replace this editorData with editor settings data. I think it'll be better to have a separate task for this as it's not related to language settings.

2023-01-12 16:40 UTC, cristianstanescu approved these changes

2023-01-13 10:11 UTC, merged